global:
  smtp_smarthost: 'smtp.gmail.com:25'
  smtp_from: 'you@gmail.com'
  smtp_require_tls: false

route:
  receiver: 'mail'
  group_by:
    - env
    - alertname
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 2m

receivers:
  - name: 'mail'
    email_configs:
     - send_resolved: true
        to: you@gmail.com
        # tls_config:
        #   insecure_skip_verify: true
        headers:
          From: monitoring@maildev.com
          Subject: '{{ template "email.default.subject" . }}'
          To: alert-all@maildev.com
        html: '{{ template "email.default.html" . }}'